language: python
sudo: false
env:
  - TOXENV=py27-django18
  - TOXENV=pypy-django18
  - TOXENV=py34-django18
  - TOXENV=py27-django19
  - TOXENV=pypy-django19
  - TOXENV=py34-django19
docsinstall: pip install -q tox
script: tox
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: jazzband/django-pipeline
    condition: "$TOXENV = py27-django19"
